### ISSUE TITLE
Include Microsoft.CSharp and System.Runtime.Serialization.Primitives in _SystemLibs 

### ISSUE THREAD

**Issue by s-tarasov** [HavenDV/H.Generators.Extensions#3]
For example https://nuget.info/packages/H.NSwag.Generator/13.17.0.67

In my scenario these libraries dont break source generator, but break [comipler server](https://github.com/dotnet/roslyn/blob/main/docs/compilers/Compiler%20Server.md) build optimization.

` CompilerServer: server failed - server rejected the request due to analyzer / generator issues 'analyzer assembly 'C:\Users\User\.nuget\packages\st.nswag.serversourcegenerator\0.0.3\analyzers\dotnet\cs\Microsoft.CSharp.dll' has MVID '77c6c890-19ac-4339-a953-ed9afe11ea30' but loaded assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID '7d43b22e-b00e-43cd-8cb6-b2ca6ec30242', analyzer assembly 'C:\Users\User\.nuget\packages\st.nswag.serversourcegenerator\0.0.3\analyzers\dotnet\cs\System.Runtime.Serialization.Primitives.dll' has MVID '81488324-7349-452a-8e77-8ef65b7bec21' but loaded assembly 'System.Runtime.Serialization.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID 'f7705c94-de51-4dcc-a98b-7535038b68ba'' - 9dfabba5-778e-4c05-9c6d-8af12a6345cd`

**Comment by HavenDV** [comment]
I have released new versions of H.Generators.Extensions 1.8.3 and H.NSwag.Generator 13.17.0.68 with this fix, please check it out

**Comment by s-tarasov** [comment]
Thanks a lot, problem solved!
