### ISSUE TITLE
Add a way to report Diagnostic

### ISSUE THREAD

**Issue by trejjam** [HavenDV/H.Generators.Extensions#5]
Hi,

I found myself in need to report Diagnostics of my own creation inside a source generator.

How do you like this code to be part of this project?
```cs
public static class IncrementalValuesProviderExtensions
{
    /// <summary>
    ///
    /// </summary>
    /// <param name="source"></param>
    /// <param name="initializationContext"></param>
    /// <typeparam name="T"></typeparam>
    /// <returns></returns>
    public static IncrementalValuesProvider<T> SelectAndReportDiagnostics<T>(
        this IncrementalValuesProvider<ResultWithDiagnostics<T>> source,
        IncrementalGeneratorInitializationContext initializationContext
    ) where T : notnull
    {
        initializationContext.RegisterSourceOutput(source
                .Where(static x => x.Diagnostics is { Length: > 0 }),
            (context, result) =>
            {
                foreach (var diagnostic in result.Diagnostics)
                {
                    context.ReportDiagnostic(diagnostic);
                }
            });

        return source
            .Where(static x => x.Result is not null)
            .Select(static (x, _) => x.Result!);
    }
}

public record struct ResultWithDiagnostics<T>(
    T? Result,
    ImmutableArray<Diagnostic> Diagnostics
) where T : notnull
{
    public ResultWithDiagnostics(T? result) : this(result, ImmutableArray<Diagnostic>.Empty)
    {
    }

    public static ResultWithDiagnostics<T> Empty => new();
}

public static class ResultWithDiagnosticsExtensions
{
    public static ResultWithDiagnostics<T> ToResultWithDiagnostics<T>(this T? result) where T : notnull => new(result);

    public static ResultWithDiagnostics<T> ToResultWithDiagnostics<T>(this T? result, ImmutableArray<Diagnostic> diagnostics) where T : notnull => new(result, diagnostics);
}

```

**Comment by HavenDV** [comment]
Yes, of course, I will gladly accept PR regarding this.
We need to consider whether your class is suitable for caching. There is a special [`EquatableArray`](https://github.com/HavenDV/H.Generators.Extensions/blob/main/src/libs/H.Generators.Extensions/EquatableArray%7BT%7D.cs) (from CommunityToolkit.Mvvm.SourceGenerators) here that can be compared.

Are you familiar with how caching works in Source Generators?

**Comment by HavenDV** [comment]
I added it and indicated you as co-author: https://github.com/HavenDV/H.Generators.Extensions/commit/187d7e46c8c4b2494aac6197566a52bf44e2723d

I didn't understand the need for `where T : notnull` in your code. This may be my misunderstanding of the nullable system in C#, but it seems redundant to me. Please check if needed I will fix it

**Comment by trejjam** [comment]
Thank you for the release.
It works without `T : notnull` also, the only difference is that you need to specify `ResultWithDiagnostics<T?>` instead of `ResultWithDiagnostics<T>` but it's not an issue. Thank you again.

**Comment by trejjam** [comment]
I know that caching is heavily used in source generators, but I was not aware that `ImmutableArray` is not enough
